new: adicionei novos links
gdcmarinho/links-uteis pull request #146
Opened 2021-08-08 19:57 UTC by Creuma-Kuzola

Adicionei novos links e também adicionei uma nova categoria, a categoria de Sites para baixar livros.
Esta categoria vai ajudar as pessoas a saberem onde baixar livros digitais de programação e design.

2021-09-21 22:11 UTC, gabrielcmarinho commented on LINKS.md
> +* [FlatIcon](https://www.flaticon.com/) - Links vetoriais e stickers para os projectos.
Link duplicado (linha 28).

2021-09-21 22:13 UTC, gabrielcmarinho commented on LINKS.md
> +* [The Net Ninja](https://www.youtube.com/channel/UCW5YeuERMmlnqo4oq8vwUpg) - Canal sobre programaçã sobre várias coisas de forma muito simples.
Não gostei muito dessa descrição, ficou muito aberto. Além disso, tem um erro na escrita no _programação_ e não é necessário adicionar ponto final na descrição do link, como dito no [guia de contribuição](https://github.com/gabrielcmarinho/links-uteis/blob/master/CONTRIBUTING.md).

2021-09-21 22:14 UTC, gabrielcmarinho commented on LINKS.md
> +*
Remover linha em branco.

2021-09-21 22:14 UTC, gabrielcmarinho commented on LINKS.md
> +
Remover linhas em branco.

2021-09-21 22:15 UTC, gabrielcmarinho commented on LINKS.md
> +* [PDF Drive](https://www.pdfdrive.com/) - PDF Drive - Considerado o mecanismo de pesquisa para arquivos PDF.
Remover ponto final.

2021-09-21 22:15 UTC, gabrielcmarinho commented on LINKS.md
> +* [Le Livros](https://lelivros.love/) - Le Livros
Melhorar na descrição do link.

2021-09-21 22:15 UTC, gabrielcmarinho commented on LINKS.md
> +* [E Livros](https://elivros.love/recentes/2) - E Livros
Melhorar na descrição do link.

2021-09-21 22:15 UTC, gabrielcmarinho commented on LINKS.md
> +* [All It Books](https://allitbooks.net/) - All It Books - Site baixar livros de TI, no idioma inglês.
Remover ponto final da descrição do link.

2021-09-21 22:15 UTC, gabrielcmarinho commented on LINKS.md
> +* [Academia Edu](https://www.academia.edu/) - Academia Edu - é um site eletrónico para acadêmicos em formato de rede social.
Remover ponto final da descrição do link.

2021-09-21 22:17 UTC, gabrielcmarinho requested changes
Qual a procedência dos livros nesses sites? Este repositório não aceita agregação de links desse meio. 😕

Outra coisa, peço que procure pelo [guia de contribuição](https://github.com/gabrielcmarinho/links-uteis/blob/master/CONTRIBUTING.md) antes de fazer uma contribuição, assim mantemos um nível de padronização nos conteúdos que aqui estão agregados.

2022-02-03 04:12 UTC, gdcmarinho commented
Devido a inatividade e a falta de esclarecimentos sobre as alterações, este PR será fechado.

2022-02-03 04:12 UTC, closed without merging