Atualiza LINKS.md
gdcmarinho/links-uteis pull request #159
Opened 2021-12-21 13:47 UTC by gentildpinto

Atualiza da página de desafio (e também o url) de URI para Beecrowd

2021-12-24 23:41 UTC, gabrielcmarinho requested changes
Tu removeu um link e não adicionou na ordem alfabética. 😕 Peço que leia o [guia de contribuição](https://github.com/gabrielcmarinho/links-uteis/blob/master/CONTRIBUTING.md) antes de fazer uma nova contribuição para o projeto.

2022-01-15 14:26 UTC, gdcmarinho commented on LINKS.md
> -* [URI](https://www.urionlinejudge.com.br/) - Desafios Programação Back-end, matemáticos e SQL. IDE integrada
Por que removeu este link?

2022-01-15 14:50 UTC, gentildpinto commented on LINKS.md
> -* [URI](https://www.urionlinejudge.com.br/) - Desafios Programação Back-end, matemáticos e SQL. IDE integrada
@gdcmarinho foi atualizado por este:
```md
[Beecrowd](https://www.beecrowd.com.br/) - Desafios Programação Back-end, matemáticos e SQL. IDE integrada
```

O nome da plataforma e a URL mudaram

2022-01-15 14:50 UTC, gentildpinto commented on LINKS.md
> -* [URI](https://www.urionlinejudge.com.br/) - Desafios Programação Back-end, matemáticos e SQL. IDE integrada
URI agora é Beecrowd

2022-01-15 17:06 UTC, gdcmarinho commented on LINKS.md
> -* [URI](https://www.urionlinejudge.com.br/) - Desafios Programação Back-end, matemáticos e SQL. IDE integrada
Entendi. Não estava sabendo dessa, @gentildpinto. Ficou melhor com esse nome! 😉

2022-01-15 17:06 UTC, gdcmarinho commented
Muito obrigado pela contribuição, @gentildpinto! Fique á vontade para fazer novas contribuições futuramente.

2022-01-15 17:07 UTC, merged