Adicionado meu podcast na aba de podcasts
gdcmarinho/links-uteis pull request #160
Opened 2021-12-28 16:45 UTC by gustavosaez

Adicionado PodApps Podcast, o primeiro podcast focado em privacidade no BR.

2022-01-09 22:26 UTC, gdcmarinho requested changes
Infelizmente não vou conseguir fazer o merge por conta dessa observação. Você conseguiria fazer essa edição?

2022-01-09 22:26 UTC, gdcmarinho commented on LINKS.md
> +* [PodApps](https://podapps.net) - Podcast e Blog focado em privacidade e proteção de dados
Este repositório tem um [guia de contribuição](https://github.com/gdcmarinho/links-uteis/blob/master/CONTRIBUTING.md) que prevê a organização dos títulos dos links ordenados alfabeticamente. Peço por gentileza que adicione este link na posição correta para poder fazer o merge.

2022-01-10 19:34 UTC, gustavosaez commented on LINKS.md
> +* [PodApps](https://podapps.net) - Podcast e Blog focado em privacidade e proteção de dados
Desculpe. Acabei de corrigir e já commitei

2022-01-12 03:53 UTC, gdcmarinho commented
Perfeito! Valeu pela contribuição, @gustavosaez 😁

2022-01-12 03:54 UTC, merged